# statefulset for mongodb
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-api-mongodb-ss
  labels:
    app: auth-api-mongodb-ss
    namespace: auth-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api-mongodb-ss
      namespace: auth-ns
  serviceName: auth-api-mongodb-svc
  template:
    metadata:
      labels:
        app: auth-api-mongodb-ss
        namespace: auth-ns
    spec:
      containers:
      - name: mongodb
        image: img-reg:5000/mongo:dev
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-admin
              key: mongo_user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-admin
              key: mongo_pass
        volumeMounts:
        - name: auth-api-mongodb-pv-claim
          mountPath: /data/db
      volumes:
      - name: auth-api-mongodb-pv-claim
        persistentVolumeClaim:
          claimName: auth-api-mongodb-pv-claim