# deployment of auth-api worker, this worker is supposed to be able to access its mongodb database 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-dp
  labels:
    app: auth-api
    namespace: auth-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth-api
        image: img-reg:5000/auth-api-kuber:dev1
        ports:
        - containerPort: 8080
          protocol: TCP
        terminationMessagePath: /opt/auth-api/logs/api.log