# persistent volume claim template
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-api-mongodb-pv-claim
  labels:
    namespace: auth-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp2
  selector:
    matchLabels:
      pvn: auth-api-mongodb-pv
      namespace: auth-ns