--service for the auth-api-dp
apiVersion: v1
kind: Service
metadata:
  name: auth-api-svc
  labels:
    app: auth-api
    namespace: auth-ns
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
  selector:
    app: auth-api