# same as auth-api-dp.yml but for grpc
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-grpc-dp
  labels:
    app: auth-grpc
    namespace: auth-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-grpc
  template:
    metadata:
      labels:
        app: auth-grpc
    spec:
      containers:
      - name: auth-grpc
        image: img-reg:5000/auth-grpc-kuber:dev1
        ports:
        - containerPort: 50051
          protocol: TCP    
        terminationMessagePath: /opt/auth-api/logs/grpc.log