version: "3.4"
services:
  auth_api_server:
    container_name: "auth_api_server"
    build:
      context: ./auth-api
      dockerfile: "Dockerfile.api"
      cache_from:
        - rust:latest
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    restart: on-failure
    links:
      - "mongodb_auth"
      - "redis_auth"
    depends_on:
      - "mongodb_auth"
      - "redis_auth"
    networks:
      - cloud_dev_internal_net
    tty: true
    ports:
      - "8080:8080"

  auth_grpc_server:
    container_name: "auth_grpc_server"
    build:
      context: ./auth-api
      dockerfile: "Dockerfile.grpc"
      cache_from:
        - rust:latest
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    restart: on-failure
    links:
      - "mongodb_auth"
      - "redis_auth"
    depends_on:
      - "mongodb_auth"
      - "redis_auth"
    networks:
      - cloud_dev_internal_net
    tty: true
    ports:
      - "50051:50051"

  redis_auth:
    image: redis:latest
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    volumes:
      - redis_data:/data
    networks:
      - cloud_dev_internal_net

  product-api:
    image: product-api:latest
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    build:
      context: ./products-api
      dockerfile: "Dockerfile"
    container_name: "product-api"
    depends_on:
      - mongodb
    networks:
      - cloud_dev_internal_net

  order-api:
    image: product-api:latest
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    build:
      context: ./order-api
      dockerfile: "Dockerfile"
    container_name: "order-api"
    depends_on:
      - mongodb
    networks:
      - cloud_dev_internal_net


  mongodb_auth:
    image: mongo:latest
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "clouddev"
      MONGO_INITDB_ROOT_PASSWORD: "12345678"
    networks:
      - cloud_dev_internal_net

  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongo
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    volumes:
      - mongodb_order_product:/data/db
    networks:
      - cloud_dev_internal_net

networks:
  cloud_dev_internal_net:
    driver: bridge

volumes:
  redis_data:
    external: false
  mongodb_data:
      driver: local
  mongodb_order_product:
    driver: local
