-- persistent volume claim template
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appname-mongodb-pv-claim
  labels:
    app: appname
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2