-- service for mongodb per application only accessible within the same cluster
apiVersion: v1
kind: Service
metadata:
  name: appname-mongodb-svc
  labels:
    app: appname
    namespace: appns
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: appname