--statefulset for redis
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: appname-redis-ss
  labels:
    app: appname
    namespace: appns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appname
      namespace: appns
  template:
    metadata:
      labels:
        app: appname
        namespace: appns
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_PASSWORD
          value: "redis"
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: appname-redis-pv-claim