-- service for redis per application only accessible within the same cluster
apiVersion: v1
kind: Service
metadata:
  name: appname-redis-svc
  labels:
    app: appname
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: appname
