--persistent volume clame template 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appname-redis-pv-claim
  labels:
    app: appname 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp2 