--persistent volume clame template 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: appname-redis-pv
  labels:
    app: appname
    namespace: appns
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  volumeMode: Filesystem
 