-- persistent volume claim template
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-api-mongodb-pv-claim
  labels:
    app: product-api
    namespace: appns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp2