--persistent volume clame template 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: product-api-redis-pv
  labels:
    app: product-api
    namespace: product-ns
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  volumeMode: Filesystem
