# service for the product-api-dp
apiVersion: v1
kind: Service
metadata:
  name: product-api-svc
  labels:
    app: product-api
    namespace: product-ns
spec:
  ports:
  - port: 50052
    targetPort: 50052
    protocol: TCP
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
  selector:
    app: product-api