# deployment of product-api worker, this worker is supposed to be able to access its mongodb database 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api-dp
  labels:
    app: product-api
    namespace: product-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
      - name: product-api
        image: img-reg:5000/product-kuber:dev
        ports:
        - containerPort: 80
          protocol: TCP