-- statefulset for mongodb
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: product-api-mongodb-ss
  labels:
    app: product-api
    namespace: product-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-api
  serviceName: product-api-mongodb-svc
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
      - name: mongodb
        image: mongo:latests
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: mongodb
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: mongodb
        - name: MONGO_INITDB_DATABASE
          value: mongodb
        volumeMounts:
        - name: mongodb-pv-claim
          mountPath: /data/db
      volumes:
      - name: mongodb-pv-claim
        persistentVolumeClaim:
          claimName: product-api-mongodb-pv-claim