# service for the order-api-dp
apiVersion: v1
kind: Service
metadata:
  name: order-api-svc
  labels:
    app: order-api
    namespace: order-ns
spec:
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP
  selector:
    app: order-api