--order-api service
apiVersion: v1
kind: Service
metadata:
  name: order-api-svc
  labels:
    app: order-api
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
  selector:
    app: order-api