-- persistent volume claim template
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-api-mongodb-pv-claim
  labels:
    app: order-api
    namespace: order-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp2