--order-api deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api-dp
  labels:
    app: order-api
    namespace: order-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - name: order-api
        image: order-api:latest
        ports:
        - containerPort: 80
          protocol: TCP