# persistent volume clame template 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: order-api-mongodb-pv
  labels:
    namespace: order-ns
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  local:
    path: /kube_pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - node3