--persistent volume clame template 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: order-api-redis-pv
  labels:
    app: order-api
    namespace: appns
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  volumeMode: Filesystem
